### ISSUE TITLE
Bower package brings dependancy on jquery 1

### ISSUE THREAD

**Issue by dvdobrovolskiy** [joseshiru/p-loading#3]
here what I got in bower.json of p-loading

 "dependencies": {
    "jquery": "1"
  },

so bower changes my jquery package 2.2.4 to 1.12.4 and this is not cool

**Comment by joseshiru** [comment]
Hi,

I'm really sorry about that issue.

I just changed the jQuery version to ">=1.5.1", so it will not modify your jQuery version again.

Thank you very much for report this issue.

**Comment by dvdobrovolskiy** [comment]
Many thnks Jose

**Comment by joseshiru** [comment]
You're welcome 😄
