### ISSUE TITLE
mask entire screen

### ISSUE THREAD

**Issue by tarponjargon** [joseshiru/p-loading#6]
Is there a way that you know of, to tell p-loading to mask the entire screen?   I am attaching to <body> (the highest element) but if the content doesn't fill the screen it looks kind of strange.  See [this screenshot](http://imgur.com/a/kH46e)

Also, thanks for doing this plugin, it's pretty sweet!

**Comment by joseshiru** [comment]
Hi Midget,

I'm sorry for the late reply, I was off for 2 weeks.

Regarding your question, definitely there is a way.

The width and height of the mask created by P-loading  is taking the 100% of size of the height and width of its parent/selected element `$('#this_is_the_selected_element').ploading({action: 'show'})`.

So, if you want to display the mask in the entire screen then, you should select an element which has width and height as 100%. In many cases people tend to give these properties to the body and HTML element:
`html,body { height: 100%; margin: 0px; padding: 0px; } `

So, after use that CSS just call $('body').ploading({action: 'show'}) and that's it.

If you don't want to display the mask in the body element, then, another way is by creating an element which has 100% of height and width and that its parent also have the same height and width (perhaps a child of the body). 



Important: be sure that element where you want to show the mask doesn't have any padding, as the mask will respect it and will not cover the whole element.

Please let me know if this fix your problem.

If you want to learn more about using 100% of height in CSS, you can check this article: http://www.tutorialrepublic.com/faq/how-to-set-a-div-height-to-100-percent-using-css.php

Cheers.

**Comment by joseshiru** [comment]
Closing this as it's not an issue and already suggest a way how to implement the mentioned feature.
